name: sunix_ledstrip_controller
description: A dart library for controlling the SunixÂ® RGB / RGBWWCW WiFi LED strip controller.
version: 1.0.1
homepage: https://github.com/robertodoering/sunix_ledstrip_controller
author: Roberto Doering <rbydoering@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.9.0
